import searchIcon from './searchIcon.svg'
import cartIcon from './cartIcon.svg'
import appstoreButton from './appstoreButton.svg'
import facebookIcon from './facebookIcon.svg'
import googleButton from './googleButton.svg'
import vkIcon from './vkIcon.svg'
import instagramIcon from './instagram.svg'
import freeProductsIcon from './freeProductsIcon.svg'
import bucketIcon from './bucketIcon.svg'
import minusIcon from './minusIcon.svg'
import plusIcon from './plusIcon.svg'
import pinkCartIcon from './pinkCartIcon.svg'
import persentIcon from './persentIcon.svg'
import pinkPaketIcon from './pinkPaketIcon.svg'
import chevronUpIcon from './chevronUpIcon.svg'
import copyIcon from './copyIcon.svg'

export {searchIcon, cartIcon,instagramIcon, vkIcon, googleButton, facebookIcon, appstoreButton, freeProductsIcon, bucketIcon, minusIcon, plusIcon, pinkPaketIcon, persentIcon, pinkCartIcon, chevronUpIcon, copyIcon};